### ISSUE TITLE
EH Trace

### ISSUE THREAD

**Issue by khabid** [victorcionca/eh_contiki#1]
Hello, 
Can I please have an example of EH trace to feed nodes?
Here is my e-mail: khaled.abid@supcom.tn
Thank you.

**Comment by victorcionca** [comment]
Hi @khabid ,

In the eh_python repository there is a datasets folder. The
https://github.com/victorcionca/eh_python/blob/master/datasets/columbia_irr_only_no_gaps.csv
file will work best with Contiki because it has a 30s measurement interval.

You have to first create your network in Cooja and export it as a csc file. Make sure that each node has the serial server enabled since the python application will be feeding the iradiance values over TCP, through the Cooja serial server.

Once you have the csc file you should start the python eh_source_server from the tools folder, including on the command line the base TCP port used for the serial servers (it's 60,000 by default), the EH dataset file, the offset in the dataset (if you want to skip ahead in the dataset, otherwise, 0), the path to the csc file and finally a shader input. The shader is so that you can create patterns of shadow and brightness at various parts of the network that are time dependent. For example, you can configure the network so that half of it is in the shadow, and this can alternate morning-afternoon.

If you are interested I have a gitlab repository for creating Cooja simulations:
https://gitlab.com/victor.cionca/cooja_sim_generator

Let me know how you get on.

Best regards,
Victor

**Comment by khabid** [comment]
This was very helpful.
Thank you Victor
